<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LibrariesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('libraries')->delete();

        \DB::table('libraries')->insert(array(
            0 =>
                array(
                    'id' => 11,
                    'title' => 'HTML5 Notes For Professionals',
                    'slug' => 'html5-notes-for-professionals',
                    'author' => 'goalkicker.com',
                    'publisher' => 'goalkicker.com',
                    'year' => '2020',
                    'isbn' => '-',
                    'lang' => 'english',
                    'pages' => '176',
                    'description' => 'Membahas mengenai cara pembuatan website dengan html 5',
                    'book_category_id' => 7,
                    'user_id' => 1,
                    'images' => 'perpus_-1685020274.png',
                    'pdf' => 'perpus_-1685020274.pdf',
                    'created_at' => '2023-05-25 13:11:14',
                    'updated_at' => '2023-05-25 13:11:14',
                ),
            1 =>
                array(
                    'id' => 12,
                    'title' => 'JavaScript Data Structures and Algorithms',
                    'slug' => 'javascript-data-structures-and-algorithms',
                    'author' => 'Sammie Bae',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'english',
                    'pages' => '351',
                    'description' => 'JavaScript Data Structures and Algorithms',
                    'book_category_id' => 1,
                    'user_id' => 1,
                    'images' => 'perpus_-1685020510.png',
                    'pdf' => 'perpus_-1685020510.pdf',
                    'created_at' => '2023-05-25 13:15:12',
                    'updated_at' => '2023-05-25 13:15:12',
                ),
            2 =>
                array(
                    'id' => 13,
                    'title' => 'Benturan NU - PKI',
                    'slug' => 'benturan-nu-pki',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '2013',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '159',
                    'description' => '-',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'perpus_Benturan NU - PKI-1685132485.jpg',
                    'pdf' => 'perpus_Benturan NU - PKI-1685132485.pdf',
                    'created_at' => '2023-05-26 20:21:25',
                    'updated_at' => '2023-05-26 20:21:25',
                ),
            3 =>
                array(
                    'id' => 14,
                    'title' => 'Analisis Sosial',
                    'slug' => 'analisis-sosial',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '241',
                    'description' => '-',
                    'book_category_id' => 1,
                    'user_id' => 1,
                    'images' => 'perpus_Analisis Sosial-1685132884.jpg',
                    'pdf' => 'perpus_Analisis Sosial-1685132884.pdf',
                    'created_at' => '2023-05-26 20:28:04',
                    'updated_at' => '2023-05-26 20:28:04',
                ),
            4 =>
                array(
                    'id' => 15,
                    'title' => 'Filsafat Ilmu',
                    'slug' => 'filsafat-ilmu',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '2013',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '95',
                    'description' => '-',
                    'book_category_id' => 2,
                    'user_id' => 1,
                    'images' => 'perpus_Filsafat Ilmu-1685133212.jpg',
                    'pdf' => 'perpus_Filsafat Ilmu-1685133212.pdf',
                    'created_at' => '2023-05-26 20:33:32',
                    'updated_at' => '2023-05-26 20:33:32',
                ),
            5 =>
                array(
                    'id' => 16,
                    'title' => 'Filsafat Islam',
                    'slug' => 'filsafat-islam',
                    'author' => 'Abdallah Baehaqi :v',
                    'publisher' => NULL,
                    'year' => NULL,
                    'isbn' => NULL,
                    'lang' => NULL,
                    'pages' => NULL,
                    'description' => '!!إقرأ صحبة',
                    'book_category_id' => 2,
                    'user_id' => 9,
                    'images' => 'perpus_-1685192467.jpg',
                    'pdf' => 'perpus_-1685192467.pdf',
                    'created_at' => '2023-05-27 13:01:07',
                    'updated_at' => '2023-05-27 13:01:07',
                ),
            6 =>
                [
                    'id' => 17,
                    'title' => 'Desain Grafis',
                    'slug' => 'desain-grafis',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => '-',
                    'pages' => '100',
                    'description' => '-',
                    'book_category_id' => 7,
                    'user_id' => 1,
                    'images' => 'Desain Grafis_PMII_UNINUS-1689006705.JPG',
                    'pdf' => 'Desain Grafis-PMII_UNINUS1689006705.pdf',
                    'created_at' => '2023-07-10 23:31:50',
                    'updated_at' => '2023-07-10 23:31:50',
                ],
            7 =>
                array(
                    'id' => 19,
                    'title' => 'Distilasi Alkena',
                    'slug' => 'distilasi-alkena',
                    'author' => 'Wira Nagara',
                    'publisher' => '-',
                    'year' => '2016',
                    'isbn' => '-',
                    'lang' => 'indonesia',
                    'pages' => '173',
                    'description' => 'Distilasi Alkena adalah sebuah proses memisahkan dua hati yang pada dasarnya tak bisa dipisahkan karena suatu ikatan perasaan. Walaupun dalam perjalanannya, hati akan tumbuh untuk bisa merelakan.',
                    'book_category_id' => 3,
                    'user_id' => 1,
                    'images' => 'Distilasi Alkena_PMII_UNINUS-1689006977.JPG',
                    'pdf' => 'Distilasi Alkena-PMII_UNINUS1689006977.pdf',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ),
            8 =>
                array(
                    'id' => 21,
                    'title' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)',
                    'slug' => 'teologi-islam-dr-harun-nasution',
                    'author' => 'DR. HARUN NASUTION',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '378-602-1602-08-7',
                    'lang' => 'indonesia',
                    'pages' => '24',
                    'description' => 'lmu kalam yang mendasari segala pokok pemikiran yang ada di dunia Islam yang kemudian menjadi  produk pemikiran yang banyak mewarnai kemajuan zaman.',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)_PMII_UNINUS-1689007748.JPG',
                    'pdf' => 'TEOLOGI ISLAM (DR. HARUN NASUTION)-PMII_UNINUS1689007748.pdf',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ),
            9 =>
                array(
                    'id' => 22,
                    'title' => 'Hasil Muspimnas',
                    'slug' => 'hasil-muspimnas',
                    'author' => 'PC IPNU IPPNU Banyumas',
                    'publisher' => 'PC IPNU IPPNU Banyumas',
                    'year' => '2022',
                    'isbn' => '378-602-1892-08-7',
                    'lang' => 'indonesia',
                    'pages' => '400',
                    'description' => 'Kegiatan Muspimnas PC IPNU IPPNU Banyumas tahun 2022 sendiri direncanakan akan berlangsung di Tulungagung mulai tanggal 17 Nopember hingga 24 Nopember 2022',
                    'book_category_id' => 1,
                    'user_id' => 1,
                    'images' => 'Hasil Muspimnas_PMII_UNINUS-1689008089.JPG',
                    'pdf' => NULL,
                    'created_at' => '2023-07-10 23:54:49',
                    'updated_at' => '2023-07-10 23:54:49',
                ),
            10 =>
                array(
                    'id' => 23,
                    'title' => 'Teori-Teori Hukum',
                    'slug' => 'teori-teori-hukum',
                    'author' => 'Penulisnya ada di title',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'indonesia',
                    'pages' => '233',
                    'description' => NULL,
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Teori-Teori Hukum_PMII_UNINUS-1689008650.JPG',
                    'pdf' => 'Teori-Teori Hukum-PMII_UNINUS1689008650.pdf',
                    'created_at' => '2023-07-11 00:04:11',
                    'updated_at' => '2023-07-11 00:04:11',
                ),
            11 =>
                array(
                    'id' => 24,
                    'title' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas',
                    'slug' => 'seperti-dendam-rindu-harus-dibayar-tuntas',
                    'author' => 'Eka Kurniawan',
                    'publisher' => 'Eka Kurniawan',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'indonesia',
                    'pages' => '254',
                    'description' => 'Eka Kurniawan',
                    'book_category_id' => 3,
                    'user_id' => 1,
                    'images' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas_PMII_UNINUS-1689008780.JPG',
                    'pdf' => 'Seperti Dendam, Rindu Harus Dibayar Tuntas-PMII_UNINUS1689008780.pdf',
                    'created_at' => '2023-07-11 00:06:22',
                    'updated_at' => '2023-07-11 00:06:22',
                ),
            12 =>
                array(
                    'id' => 25,
                    'title' => 'Sejarah Ideologi Dunia',
                    'slug' => 'sejarah-ideologi-dunia',
                    'author' => 'Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                    'publisher' => 'Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '46',
                    'description' => 'Sejarah Ideologi Dunia Kapitalisme, Sosialisme, Komunisme, Fasisme, Anarkisme, Anarkisme dan Marxisme, Konservatisme by Nur Sayyid Santoso Kristeva, S.Pd.I, M.A.',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Sejarah Ideologi Dunia_PMII_UNINUS-1689009015.JPG',
                    'pdf' => 'Sejarah Ideologi Dunia-PMII_UNINUS1689009015.pdf',
                    'created_at' => '2023-07-11 00:10:15',
                    'updated_at' => '2023-07-11 00:10:15',
                ),
            13 =>
                array(
                    'id' => 26,
                    'title' => 'Sejarah Tuhan',
                    'slug' => 'sejarah-tuhan',
                    'author' => 'Karen Armstrong',
                    'publisher' => 'Mizan Pustaka',
                    'year' => '2014',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '280',
                    'description' => 'Kisah 4.000 Tahun Pencarian Tuhan dalam Agama-Agama Manusia',
                    'book_category_id' => 2,
                    'user_id' => 1,
                    'images' => 'Sejarah Tuhan_PMII_UNINUS-1689009285.JPG',
                    'pdf' => 'Sejarah Tuhan-PMII_UNINUS1689009285.pdf',
                    'created_at' => '2023-07-11 00:14:46',
                    'updated_at' => '2023-07-11 00:14:46',
                ),
            14 =>
                array(
                    'id' => 27,
                    'title' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                    'slug' => 'sebuah-seni-untuk-bersikap-bodo-amat',
                    'author' => 'by Mark Manson',
                    'publisher' => 'nda tau juga',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '256',
                    'description' => 'Sebuah Seni untuk Bersikap Bodo Amat adalah buku pertama karya Mark Manson, seorang narablog kenamaan dengan lebih dari 2 juta pembaca.',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Sebuah Seni untuk Bersikap Bodo Amat_PMII_UNINUS-1689009522.JPG',
                    'pdf' => 'Sebuah Seni untuk Bersikap Bodo Amat-PMII_UNINUS1689009522.pdf',
                    'created_at' => '2023-07-11 00:18:45',
                    'updated_at' => '2023-07-11 00:18:45',
                ),
            15 =>
                array(
                    'id' => 28,
                    'title' => 'Retorika Aristoteles',
                    'slug' => 'retorika-aristoteles',
                    'author' => 'ga tau',
                    'publisher' => 'nda tau juga',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '120',
                    'description' => 'Retorika Aristoteles adalah risalah Yunani kuno tentang seni persuasi, yang berasal dari abad ke-4 SM',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Retorika Aristoteles_PMII_UNINUS-1689009733.jpg',
                    'pdf' => 'Retorika Aristoteles-PMII_UNINUS1689009733.pdf',
                    'created_at' => '2023-07-11 00:22:13',
                    'updated_at' => '2023-07-11 00:22:13',
                ),
            16 =>
                array(
                    'id' => 29,
                    'title' => 'Orang-orang Di Persimpangan Kiri Jalan',
                    'slug' => 'orang-orang-di-persimpangan-kiri-jalan',
                    'author' => 'Soe Hok Gie',
                    'publisher' => 'ya nda tau kok tanya saya',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '332',
                    'description' => 'Orang-Orang Di Persimpangan Kiri Jalan salah satu karya Soe Hok Gie tentang pemberontakan PKI di Madiun ini dianyam demikian rupa seakan-akan kita membaca sebuah novel sejarah dramatis yang menegangkan',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Orang-orang Di Persimpangan Kiri Jalan_PMII_UNINUS-1689010019.JPG',
                    'pdf' => 'Orang-orang Di Persimpangan Kiri Jalan-PMII_UNINUS1689010019.pdf',
                    'created_at' => '2023-07-11 00:27:05',
                    'updated_at' => '2023-07-11 00:27:05',
                ),
            17 =>
                array(
                    'id' => 30,
                    'title' => 'Perempuan Berbicara Kretek',
                    'slug' => 'perempuan-berbicara-kretek',
                    'author' => 'ga tau',
                    'publisher' => 'ya nda tau kok tanya saya',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '334',
                    'description' => 'Secara umum buku ini dibagi dalam empat bagian. Pertama, Ritus. Keseharian, di sini mereka bercerita tentang kehadiran kretek dalam keseharian mereka',
                    'book_category_id' => 6,
                    'user_id' => 1,
                    'images' => 'Perempuan Berbicara Kretek_PMII_UNINUS-1689010155.JPG',
                    'pdf' => 'Perempuan Berbicara Kretek-PMII_UNINUS1689010155.pdf',
                    'created_at' => '2023-07-11 00:29:18',
                    'updated_at' => '2023-07-11 00:29:18',
                ),
            18 =>
                array(
                    'id' => 31,
                    'title' => 'Nusa Jawa Silang Budaya',
                    'slug' => 'nusa-jawa-silang-budaya',
                    'author' => 'ga tau',
                    'publisher' => 'ya nda tau kok tanya saya',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '358',
                    'description' => 'silang budaya kajian sejarah terpadu / Denys Lombard ; alih lang, Winarsih Partaningrat Arifin, Rahayu S. Hidayat, Nini Hidayati Yusuf.',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Nusa Jawa Silang Budaya_PMII_UNINUS-1689010294.JPG',
                    'pdf' => 'Nusa Jawa Silang Budaya-PMII_UNINUS1689010294.pdf',
                    'created_at' => '2023-07-11 00:31:39',
                    'updated_at' => '2023-07-11 00:31:39',
                ),
            19 =>
                array(
                    'id' => 32,
                    'title' => 'My Public Speaking',
                    'slug' => 'my-public-speaking',
                    'author' => 'Hilbram Dunar',
                    'publisher' => 'ya nda tau kok tanya saya',
                    'year' => 'ya nda tau kok tanya saya',
                    'isbn' => 'ya nda tau kok tanya saya',
                    'lang' => 'indonesia',
                    'pages' => '192',
                    'description' => 'ditulis berdasarkan pengalaman Hilbram Dunar selama dua belas tahun menjadi seorang public speaker. Bermula sebagai penyiar di MS Tri FM,',
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'My Public Speaking_PMII_UNINUS-1689010388.JPG',
                    'pdf' => 'My Public Speaking-PMII_UNINUS1689010388.pdf',
                    'created_at' => '2023-07-11 00:33:09',
                    'updated_at' => '2023-07-11 00:33:09',
                ),
            20 =>
                array(
                    'id' => 33,
                    'title' => 'Aswaja',
                    'slug' => 'aswaja',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '48',
                    'description' => 'Buku panduan Aswaja PMII',
                    'book_category_id' => 1,
                    'user_id' => 1,
                    'images' => 'Aswaja_PMII_UNINUS-1689010820.jpg',
                    'pdf' => 'Aswaja-PMII_UNINUS1689010820.pdf',
                    'created_at' => '2023-07-11 00:40:20',
                    'updated_at' => '2023-07-11 00:40:20',
                ),
            21 =>
                array(
                    'id' => 34,
                    'title' => 'Negeri Para Bedebah',
                    'slug' => 'negeri-para-bedebah',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '444',
                    'description' => NULL,
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Negeri Para Bedebah_PMII_UNINUS-1689010940.jpg',
                    'pdf' => 'Negeri Para Bedebah-PMII_UNINUS1689010940.pdf',
                    'created_at' => '2023-07-11 00:42:24',
                    'updated_at' => '2023-07-11 00:42:24',
                ),
            22 =>
                array(
                    'id' => 35,
                    'title' => 'MADILOG',
                    'slug' => 'madilog',
                    'author' => 'Tan Malaka',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '388',
                    'description' => NULL,
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'MADILOG_PMII_UNINUS-1689011080.jpg',
                    'pdf' => 'MADILOG-PMII_UNINUS1689011080.pdf',
                    'created_at' => '2023-07-11 00:44:41',
                    'updated_at' => '2023-07-11 00:44:41',
                ),
            23 =>
                array(
                    'id' => 36,
                    'title' => 'Seni Perang Sun Tzu',
                    'slug' => 'seni-perang-sun-tzu',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '122',
                    'description' => NULL,
                    'book_category_id' => 4,
                    'user_id' => 1,
                    'images' => 'Seni Perang Sun Tzu_PMII_UNINUS-1689011175.jpg',
                    'pdf' => 'Seni Perang Sun Tzu-PMII_UNINUS1689011175.pdf',
                    'created_at' => '2023-07-11 00:46:15',
                    'updated_at' => '2023-07-11 00:46:15',
                ),
            24 =>
                array(
                    'id' => 37,
                    'title' => 'Modul NDP',
                    'slug' => 'modul-ndp',
                    'author' => '-',
                    'publisher' => '-',
                    'year' => '-',
                    'isbn' => '-',
                    'lang' => 'Indonesia',
                    'pages' => '45',
                    'description' => NULL,
                    'book_category_id' => 1,
                    'user_id' => 1,
                    'images' => 'Modul NDP_PMII_UNINUS-1689011537.jpg',
                    'pdf' => 'Modul NDP-PMII_UNINUS1689011537.pdf',
                    'created_at' => '2023-07-11 00:52:17',
                    'updated_at' => '2023-07-11 00:52:17',
                ),
        ));
    }
}
